const { activityService } = require('./src/services/activity.service');
const { query } = require('./src/database/connection');

async function test() {
  try {
    // 1. Find a user
    const userRes = await query('SELECT id, email FROM users LIMIT 1');
    if (userRes.rows.length === 0) {
      console.log('No users found in DB');
      return;
    }
    const user = userRes.rows[0];
    console.log(`Testing with user: ${user.email} (${user.id})`);

    // 2. Update last active
    console.log('Updating last active...');
    await activityService.updateLastActive(user.id);
    
    // 3. Log activity
    console.log('Logging activity...');
    await activityService.logActivity({
      userId: user.id,
      type: 'test_activity',
      description: 'Activity generated by diagnostic script'
    });

    // 4. Verify
    const verifyUser = await query('SELECT email, last_active_at FROM users WHERE id = $1', [user.id]);
    console.log('User last_active_at:', verifyUser.rows[0].last_active_at);

    const verifyAct = await query('SELECT count(*) FROM activities WHERE user_id = $1', [user.id]);
    console.log('Activities for user:', verifyAct.rows[0].count);

  } catch (err) {
    console.error('Test failed:', err);
  }
}

// Simple mock for path alias if needed, but here we use relative
test();
